name = "RepLieGroups"
uuid = "f07d36f2-91c4-427a-b67b-965fe5ebe1d2"
version = "0.1.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LocalRegistry = "89398ba2-070a-4b16-a995-9893c55d93cf"
PartialWaveFunctions = "793d2195-304b-438e-bbb1-bc33c872ac39"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Combinatorics = "1.0"
LinearAlgebra = "1.10"
PartialWaveFunctions = "0.2.0"
SparseArrays = "1.10"
StaticArrays = "1.5"
julia = "1.10, 1.11"

[extras]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SpheriCart = "5caf2b29-02d9-47a3-9434-5931c85ba645"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WignerD = "87c4ff3e-34df-11e9-37a7-516cea4e0402"

[targets]
test = ["Test", "WignerD", "Rotations", "BlockDiagonals", 
        "SpheriCart", "Random"]
