name = "RepLieGroups"
uuid = "f07d36f2-91c4-427a-b67b-965fe5ebe1d2"
authors = ["Christoph Ortner <christohortner@gmail.com> and contributors"]
version = "0.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials4ML = "03c4bcba-a943-47e9-bfa1-b1661fc2974f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
